context:
  name: "mostlyai"
  version: "4.7.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mostlyai-${{ version }}.tar.gz
  sha256: 1f9a4a8ffd3507d813da53000f168f6b5434e9055f978d0a32510c6305b2df8d

build:
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.4.2,<3
    - httpx >=0.25.0
    - pandas >=2.0.0
    - pyarrow >=16.0.0
    - rich >=13.7.0
    - psutil >=5.9.5
    - requests >=2.31.0
    - typer >=0.9.0
    - semantic_version >=2.10.0
    - gunicorn >=23.0.0
    - environs >=9.5.0
    - schema >=0.7.5
    - python-xxhash >=3.2.0
    - greenlet >=3.1.1
    - pycryptodomex >=3.10.0
    - ipywidgets >=8.1.0
    - python-duckdb >=1.2.1
    - sqlparse >=0.5.3
    # Extra: local
    - mostlyai-engine ==1.4.2
    - mostlyai-qa ==1.9.6
    - fastapi >=0.115.6,<0.116
    - uvicorn >=0.34.0,<0.35
    - python-multipart >=0.0.20
    - pytorch >=2.6.0,<2.6.1
    - torchaudio >=2.6.0,<2.6.1
    - torchvision >=0.21.0,<0.21.1
    - joblib >=1.4.2
    - sqlalchemy >=2.0.0
    - sshtunnel >=0.4.0,<0.5
    - networkx >=3.0,<4
    - xlsxwriter >=3.1.9,<4
    - openpyxl >=3.1.5
    - filelock >=3.16.1
    - s3fs >=2023.1.0
    - gcsfs >=2023.1.0
    - cloudpathlib >=0.17.0
    - smart-open >=6.3.0
    - azure-storage-blob >=12.16.0
    - adlfs >=2023.4.0
tests:
  - python:
      python_version: ${{ python_min }}.*
      # mostlyai-qa currently fails pip check
      # See https://github.com/conda-forge/mostlyai-qa-feedstock/blob/main/recipe/recipe.yaml#L62
      pip_check: false
      imports:
        - mostlyai

about:
  summary: Synthetic Data SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mostly-ai/mostlyai

extra:
  recipe-maintainers:
    - AndreasAlbertQC
